---
title: "BiasVarianceGraphic.rmd"
author: "Shan Chen"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
biasVarTO3 <- function(form,sizeDS,numDS,x0){
  allVals <- matrix(ncol=2,nrow=numDS)
  for(m in 1:numDS){
    mod <- lm(formula(form),buildData(f,sizeDS,sig))
    pred <- predict(mod,newdata=data.frame(x=x0))
    allVals[m,1] <- pred
  }
  allVals[,2] <- f(x0)+rnorm(numDS,0,sig)
  
  allVals.df <- data.frame(pred=allVals[,1],true=allVals[,2])
  mse <- with(allVals.df,mean((pred-true)^2))
  var0 <- with(allVals.df,var(pred))
  bias2 <- with(allVals.df,mean(pred-true))^2
  noise <- sig^2
  c(mse,var0,bias2,noise)
}
```
build data
```{r}
buildData <- function(func,sizeDS,sig,xMin = -1, xMax = 1){
##predictor
x<-runif(sizeDS,xMin, xMax) # inputs
## Repsonse
y<-func(x)+rnorm(sizeDS,0,sig) #realized values f(x)+noise
## Put in a data frame
data.frame(x,y)
}
```
A collection of underlying "true" functions.
```{r}
f1 <- function(x) x+2
f2 <- function(x) (x-1)*(x+1)
f3 <- function(x) x*(x-1)*(x+1)
form1 <- "y~x"
form2 <- "y~x+I(x^2)"
form3 <- "y~x+I(x^2)+I(x^3)"
sig <-1.75
sizeDS <- 50
numReps <- 100 

K <- 101
## Range
xMin <- -1
xMax <- 1
xVals<-seq(xMin, xMax,length=K)
```

```{r}
f <-f1
resVals1 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals1[k,] <- biasVarTO3(form1,sizeDS,numReps,xVals[k])
}
resVals2 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals2[k,] <- biasVarTO3(form2,sizeDS,numReps,xVals[k])
}
resVals3 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals3[k,] <- biasVarTO3(form3,sizeDS,numReps,xVals[k])
}
```

```{r}
#Flex 1
data1.df <- data.frame(resVals1,deg=1)
names(data1.df) <- c("mse","var","bias2","noise","deg")
#Flex 2
data2.df <- data.frame(resVals2,deg=2)
names(data2.df) <- c("mse","var","bias2","noise","deg")
#Flex 3
data3.df <- data.frame(resVals3,deg=3)
names(data3.df) <- c("mse","var","bias2","noise","deg")

data.df <- bind_rows(data1.df,data2.df,data3.df)
##Add x values..note the repetition (one set for each flex value)
data.df$x <- rep(xVals,3)
```

```{r}
data.df %>%
select(-noise) %>%
gather(type,err,c(mse,var,bias2)) %>%
ggplot()+
geom_point(aes(x,err,color=type),size=.5)+
facet_grid(type~deg,scale="free_y")+ ##free_y allows different scales
labs(title=sprintf("Bias/Var/MSE for Linear Model\n sigma=%s",sig))
```
2 degree:
```{r}
f <-f2
resVals1 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals1[k,] <- biasVarTO3(form1,sizeDS,numReps,xVals[k])
}
resVals2 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals2[k,] <- biasVarTO3(form2,sizeDS,numReps,xVals[k])
}
resVals3 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals3[k,] <- biasVarTO3(form3,sizeDS,numReps,xVals[k])
}
```

```{r}
#Flex 1
data1.df <- data.frame(resVals1,deg=1)
names(data1.df) <- c("mse","var","bias2","noise","deg")
#Flex 2
data2.df <- data.frame(resVals2,deg=2)
names(data2.df) <- c("mse","var","bias2","noise","deg")
#Flex 3
data3.df <- data.frame(resVals3,deg=3)
names(data3.df) <- c("mse","var","bias2","noise","deg")

data.df <- bind_rows(data1.df,data2.df,data3.df)
##Add x values..note the repetition (one set for each flex value)
data.df$x <- rep(xVals,3)
```

```{r}
data.df %>%
select(-noise) %>%
gather(type,err,c(mse,var,bias2)) %>%
ggplot()+
geom_point(aes(x,err,color=type),size=.5)+
facet_grid(type~deg,scale="free_y")+ ##free_y allows different scales
labs(title=sprintf("Bias/Var/MSE for Quadratic Model\n sigma=%s",sig))
```
#3rd
```{r}
f <-f3
resVals1 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals1[k,] <- biasVarTO3(form1,sizeDS,numReps,xVals[k])
}
resVals2 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals2[k,] <- biasVarTO3(form2,sizeDS,numReps,xVals[k])
}
resVals3 <- matrix(nrow=K,ncol=4)
for(k in 1:K){
resVals3[k,] <- biasVarTO3(form3,sizeDS,numReps,xVals[k])
}
```

```{r}
#Flex 1
data1.df <- data.frame(resVals1,deg=1)
names(data1.df) <- c("mse","var","bias2","noise","deg")
#Flex 2
data2.df <- data.frame(resVals2,deg=2)
names(data2.df) <- c("mse","var","bias2","noise","deg")
#Flex 3
data3.df <- data.frame(resVals3,deg=3)
names(data3.df) <- c("mse","var","bias2","noise","deg")

data.df <- bind_rows(data1.df,data2.df,data3.df)
##Add x values..note the repetition (one set for each flex value)
data.df$x <- rep(xVals,3)
```

```{r}
data.df %>%
select(-noise) %>%
gather(type,err,c(mse,var,bias2)) %>%
ggplot()+
geom_point(aes(x,err,color=type),size=.5)+
facet_grid(type~deg,scale="free_y")+ ##free_y allows different scales
labs(title=sprintf("Bias/Var/MSE for 3rd Model\n sigma=%s",sig))
```
MSE and bias2 does not change much as the flexibility of the model changes. But the variance error rate raises as flexibility raises which make sense based on variance's defination.